name: weakards
channels:
  - conda-forge
  - menpo
  - pytorch
dependencies:
  - python=3.7
  - scipy<1.3
  - pyqt
  - matplotlib
  - pyyaml
  - pytorch
  - torchvision
  - opencv
  - tensorboardx
  - ipython
  - pip
  - pip:
    - pandas
    - prettytable
    - pytorch-lightning
    - scikit-learn
    - imbalanced-learn
    - ventmap
    - wfdb
